version: 2.1

executors:
  go-executor:
    docker:
      - image: cimg/go:1.22.0
    resource_class: large

orbs:
  github-cli: circleci/github-cli@2.3.0

jobs:
  build-caddy-all:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Get XCADDY
          command: |
            go version
            go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - run:
          name: Build Binaries
          command: |
            sh ./scripts/build-all.sh
            chmod +x caddy-linux-amd64
            ./caddy-linux-amd64 version
            mkdir artifacts
            mv caddy-linux-amd64 caddy-linux-arm64 caddy-windows-amd64.exe caddy-windows-arm64.exe ./artifacts
      - run:
          name: Get Binary Version
          command: |
            ls ./artifacts
            ./artifacts/caddy-linux-amd64 version
            CADDY=$(./artifacts/caddy-linux-amd64 version)
            echo "version=$( echo $CADDY | head -n1 | cut -d " " -f1 )" >> $BASH_ENV
            mkdir gitclone
      - github-cli/setup
      - github-cli/clone:
          repo: caddy
          dir: ./gitclone
      - run:
          name: Create Release
          command: |
            cd ./gitclone
            if gh release view $version >/dev/null 2>&1; then
                gh release delete $version --cleanup-tag --yes
            fi
            cd ../
            gh release create $version --title "Binary Update - Caddy "$version"" --notes "Automated release from CircleCI" --repo igorferreir4/caddy ./artifacts/*

workflows:
  build-caddy:
    jobs:
      - build-caddy-all