version: 2.1

# orbs:
#   go: circleci/go@1.10.0

jobs:
  build-caddy:
    docker:
      - image: cimg/go:1.21.5
    steps:
      - checkout
      # - go/mod-download
      - run:
          name: Get XCADDY
          command: |
            go version
      #       go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      # - run:
      #     name: Build Binaries
      #     command: |
      #       sh ./scripts/caddybuild-linux-amd64.sh
      #       sh ./scripts/caddybuild-linux-arm64.sh
      #       sh ./scripts/caddybuild-win-amd64.sh
      #       sh ./scripts/caddybuild-win-arm64.sh
      #       chmod +x caddy-linux-amd64
      # - run:
      #     name: Get Binary Version
      #     command: |
      #       CADDY=$(./caddy-linux-amd64 version)
      #       vr="${CADDY}"
      #       echo "version=$( echo $vr | head -n1 | cut -d " " -f1 )" >> $BASH_ENV
      #       echo "tag_name=$( echo $vr | head -n1 | cut -d " " -f1 )" >> $BASH_ENV
      # - run:
      #     name: Create Release
      #     command: |
      #       curl -s -X POST https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/releases \
      #       -H "Authorization: token $GITHUB_TOKEN" \
      #       -H "Content-Type: application/json" \
      #       -d '{
      #         "tag_name": "'"$tag_name"'",
      #         "target_commitish": "master",
      #         "name": "Binary Update - Caddy '"$version"'",
      #         "body": "Release notes: '"$html_url"'",
      #         "draft": false,
      #         "prerelease": false
      #       }'

workflows:
  build:
    jobs:
      - build-caddy