version: 2.1

executors:
  go-executor:
    docker:
      - image: cimg/go:1.21.5
    resource_class: large

orbs:
  github-release: h-matsuo/github-release@0.1.3

jobs:
  build-caddy:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Get XCADDY
          command: |
            go version
            go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - run:
          name: Build Binaries
          command: |
            mkdir artifacts
            sh ./scripts/caddybuild-linux-amd64.sh & \
            sh ./scripts/caddybuild-linux-arm64.sh & \
            sh ./scripts/caddybuild-win-amd64.sh & \
            sh ./scripts/caddybuild-win-arm64.sh & \
            wait
            mv caddy-linux-amd64 caddy-linux-arm64 caddy-windows-amd64.exe caddy-windows-arm64.exe artifacts/
      - persist_to_workspace:
          root: ./artifacts
          paths:
            - caddy-linux-amd64
            - caddy-linux-arm64
            - caddy-windows-amd64.exe
            - caddy-windows-arm64.exe
      - store_artifacts:
          path: ./artifacts            

  create-release:
    description: Publish a new release tagged `vX.Y.Z`.
    executor: github-release/default
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: Get Binary Version
          command: |
            ls ./artifacts
            ./artifacts/caddy-linux-amd64 version
            CADDY=$(./artifacts/caddy-linux-amd64 version)
            echo "version=$( echo $CADDY | head -n1 | cut -d " " -f1 )" >> $BASH_ENV
      - github-release/create:
          tag: "$version"
          title: Binary Update - Caddy "$version"
          description: This release is version "$version".
          file-path: ./artifacts
          user: igorferreir4
          repository: caddy

workflows:
  build-caddy:
    jobs:
      - build-caddy
      - create-release:
          requires:
            - build-caddy