version: 2.1

executors:
  go-executor:
    docker:
      - image: cimg/go:1.21.5
    resource_class: large

orbs:
  github-release: h-matsuo/github-release@0.1.3

jobs:
  build-caddy-linux-amd64:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Get XCADDY
          command: |
            go version
            go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - run:
          name: Build Binaries
          command: |
            sh ./scripts/caddybuild-linux-amd64.sh
            chmod +x caddy-linux-amd64
            ./caddy-linux-amd64 version
      # - run:
      #     name: Get Binary Version
      #     command: |
      #       CADDY=$(./caddy-linux-amd64 version)
      #       vr="${CADDY}"
      #       echo "version=$( echo $vr | head -n1 | cut -d " " -f1 )" >> $BASH_ENV
      #       echo "tag_name=$( echo $vr | head -n1 | cut -d " " -f1 )" >> $BASH_ENV
      - persist_to_workspace:
          root: .
          paths:
            - caddy-linux-amd64

  build-caddy-linux-arm64:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Get XCADDY
          command: |
            go version
            go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - run:
          name: Build Binaries
          command: |
            sh ./scripts/caddybuild-linux-arm64.sh
      - persist_to_workspace:
          root: .
          paths:
            - caddy-linux-arm64

  build-caddy-win-amd64:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Get XCADDY
          command: |
            go version
            go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - run:
          name: Build Binaries
          command: |
            sh ./scripts/caddybuild-win-amd64.sh
      - persist_to_workspace:
          root: .
          paths:
            - caddy-windows-amd64.exe

  build-caddy-win-arm64:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Get XCADDY
          command: |
            go version
            go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - run:
          name: Build Binaries
          command: |
            sh ./scripts/caddybuild-win-arm64.sh
      - persist_to_workspace:
          root: .
          paths:
            - caddy-windows-arm64.exe

  create-release:
    description: Publish a new release tagged `vX.Y.Z`.
    executor: github-release/default
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: Get Binary Version
          command: |
            ls ./artifacts
            CADDY=$(./artifacts/caddy-linux-amd64 version)
            vr="${CADDY}"
            echo "version=$( echo $vr | head -n1 | cut -d " " -f1 )" >> $BASH_ENV
            echo "tag_name=$( echo $vr | head -n1 | cut -d " " -f1 )" >> $BASH_ENV
      - github-release/create:
          tag: "$version"
          title: "Binary Update - Caddy $version"
          description: This release is version "$version" .
          file-path: ./artifacts
          user: igorferreir4
          repository: caddy

workflows:
  build-caddy:
    jobs:
      - build-caddy-linux-amd64
      - build-caddy-linux-arm64
      - build-caddy-win-amd64
      - build-caddy-win-arm64
      - create-release:
          requires:
            - build-caddy-linux-amd64
            - build-caddy-linux-arm64
            - build-caddy-win-amd64
            - build-caddy-win-arm64