### This section defines the action ###

# Name of the action
name: Caddy

on:
  # Allows you to manually run the action from inside the Actions tab of the repo
  workflow_dispatch: 

# See https://docs.github.com/en/actions/using-workflows/triggering-a-workflow for more options

### This section defines the job steps for the action ###
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19'

      # Get xcaddy go module
      - name: Get XCADDY
        run: |
          go version
          go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      # Cache
      - name: Cache the build cache
        uses: actions/cache@v3
        with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

      # Check out local repo
      - name: Pull Local Repo
        uses: actions/checkout@v3

      # Build Binaries and set them to executable
      - name: Build Binaries
        env:
          CGO_ENABLED: 0
          GOOS: ${{ matrix.goos }}
        run: |
          sh ./scripts/caddybuild-linux-amd64.sh
          sh ./scripts/caddybuild-linux-arm64.sh
          sh ./scripts/caddybuild-win-amd64.sh
          sh ./scripts/caddybuild-win-arm64.sh
          chmod +x caddy-amd64
          chmod +x caddy-arm64

      # Get the new version of the binary package
      - name: Get Binary Version
        id: caddy_version
        run: |
          CADDY=$(./caddy-amd64 version)
          vr="${CADDY}"
          echo "version=$( echo $vr | head -n1 | cut -d " " -f1 )" >> $GITHUB_OUTPUT
          echo "tag_name=$( echo $vr | head -n1 | cut -d " " -f1 )" >> $GITHUB_OUTPUT

      # echo "::set-output name=version::$( echo $vr | head -n1 | cut -d " " -f1 )"
      # echo "::set-output name=tag_name::$( echo $vr | head -n1 | cut -d " " -f1 )"
          
      # Create release in repository and attach binaries
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ steps.caddy_version.outputs.tag_name }}"
          name: Binary Update - Caddy ${{ steps.caddy_version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Release notes: ${{ steps.get_release_notes.outputs.html_url }}
          files: |
            caddy-amd64
            caddy-arm64
            caddy-amd64.exe
            caddy-arm64.exe